# This is the syntax of the docker compose we will use.
# version: '3.9'

# This is the main block. We have app and we want to build our docker file inside our current directory.
# Adding dev=true to overwrite the DEV in dockerfile.
# Maps port 8000 from our locak machine to that of our docker container
# Volumes maps our changes from our local project to the container project
# Finally the command is what we run the service with. 
services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"